version: "3"
services: 
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
  
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "3000:80"

  server:
    # links: 
    #   - mongo
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - "5000:5000"
    # depends_on:   
    #   - mongo
    volumes: 
      - /app/node_modules
      - ./server:/app

  # mongo:  
  #   restart: always
  #   build: 
  #     dockerfile: Dockerfile
  #     context: ./mongo
  #   ports: 
  #     - "27017:270d17"
